### PR TITLE
fix(helm): Add NODE_NAME env var to the vgpu-monitor container from spec.nodeName

### LINKED ISSUE #686: Fix: Add NODE_NAME env var to vgpu-monitor container in Helm chart for nodeName retrieval
### Description:
The PR (#683) uses `nodeName := os.Getenv(util.NodeNameEnvName)` to retrieve the node name. However, the Helm chart does not set the `NODE_NAME` environment variable for the container. This causes nodeName to be empty when deployed via Helm.

### Proposed Solution:
Update the Helm chart to include the NODE_NAME environment variable by adding the following to the vgpu-monitor container spec:

```yaml
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
```

### PR DESCRIPTION
**Pull request by Nimbus318**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #686

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by lengrongfu** [comment]
@Nimbus318 can you rebase main branch? because having resolve code lint question.

**Comment by Nimbus318** [comment]
@lengrongfu Rebased

**Pull request merged**
