### PR TITLE
fix: exception happen when creating multiple ascend-gpu pods concurrently

### PR DESCRIPTION
**Pull request by lijm87**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: exception occurred while creating multiple pods with ascend gpu concurrently

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by archlitchi** [comment]
yes, nodelock is necessary for ascend jobs, but you need to implement 'release lock' part in 'ascend-device-plugin' for it to work

**Comment by lijm87** [comment]
> yes, nodelock is necessary for ascend jobs, but you need to implement 'release lock' part in 'ascend-device-plugin' for it to work

done. the PR in 'ascend-device-plugin': https://github.com/Project-HAMi/ascend-device-plugin/pull/7

**Comment by lijm87** [comment]
> yes, nodelock is necessary for ascend jobs, but you need to implement 'release lock' part in 'ascend-device-plugin' for it to work

done. together with PR in 'ascend-device-plugin': https://github.com/Project-HAMi/ascend-device-plugin/pull/7

**Comment by archlitchi** [comment]
hi, could you resolve this conflict? i'm going to integrate this PR in HAMi v2.5

**Comment by lijm87** [comment]
fix conflict

**Pull request merged**
