### PR TITLE
Fix: Refactor the license based on the approaches used in OpenSearch and ElasticSearch.

### PR DESCRIPTION
**Pull request by haitwang-cloud**
**What type of PR is this?**
/kind documentation

### **What this PR does / why we need it**:

Refactor the license using the methods applied in OpenSearch and ElasticSearch:
- Update the license according to the [OpenSearch license](https://github.com/opensearch-project/OpenSearch/blob/581771053c324e0774c3309ec9806d53d99f9f35/libs/core/src/main/java/org/opensearch/Build.java).
- Add `NOTICE.txt` based on the [OpenSearch NOTICE.txt](https://github.com/opensearch-project/OpenSearch/blob/main/NOTICE.txt).

### **Special notes for your reviewer**:
- The original license from NVIDIA CORPORATION has been preserved.
- A new license section has been added for The HAMi Authors.
- No modifications have been made to the original codebase beyond the addition of the new license section.
### **Does this PR introduce a user-facing change?**:
No, this PR does not introduce any user-facing changes. It is purely a documentation update to ensure proper licensing and attribution

### CODE REVIEW

**Comment by haitwang-cloud** [comment]
@archlitchi PTAL

**Comment by wawa0210** [comment]
I can't tell whether the current changes will cause legal risks. Can you explain it in detail?

**Comment by wawa0210** [comment]
> @wawa0210 I am following the the provided license terms, Section 4 in https://www.apache.org/licenses/LICENSE-2.0 to meet the following conditions:
> 
> * You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the
> * Derivative Works;：You must keep all the copyright, patent, trademark, and attribution notices from the original software in the source code of any derivative works you distribute.

Thank you for your reply. Can you please research how other open source projects handle this situation?

**Comment by haitwang-cloud** [comment]
> > @wawa0210 I am following the the provided license terms, Section 4 in https://www.apache.org/licenses/LICENSE-2.0 to meet the following conditions:
> > 
> > * You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the
> > * Derivative Works;：You must keep all the copyright, patent, trademark, and attribution notices from the original software in the source code of any derivative works you distribute.
> 
> Thank you for your reply. Can you please research how other open source projects handle this situation?

**Comment by haitwang-cloud** [comment]
@wawa0210  Sorry, I’m not sure what you expect next.

**Comment by haitwang-cloud** [comment]
@wawa0210 ping

**Comment by haitwang-cloud** [comment]
Refactor the license using the methods applied in OpenSearch and ElasticSearch:
- Update the license according to the [OpenSearch license](https://github.com/opensearch-project/OpenSearch/blob/581771053c324e0774c3309ec9806d53d99f9f35/libs/core/src/main/java/org/opensearch/Build.java).
- Add `NOTICE.txt` based on the [OpenSearch NOTICE.txt](https://github.com/opensearch-project/OpenSearch/blob/main/NOTICE.txt).

**Comment by wawa0210** [comment]
👍

**Review by wawa0210 — APPROVED** [review]

**Pull request merged**
