### PR TITLE
add scheduler command

### PR DESCRIPTION
**Pull request by CoderTH**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Add scheduling startup parameters

image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by CoderTH** [comment]
@lengrongfu @wawa0210 
cc

**Comment by lengrongfu** [comment]
Thank you, add helm param to set scheduler policy.

**Review by wawa0210 — APPROVED** [review]

**Review by wawa0210 — APPROVED** [review]

**Review by archlitchi — APPROVED** [review]
/lgtm

**Pull request merged**
