### PR TITLE
Fix code scanning alert-Incorrect conversion between integer types

### LINKED ISSUE #551: Fix code scanning alert - Incorrect conversion between integer types
Tracking issue for:
- [ ] https://github.com/Project-HAMi/HAMi/security/code-scanning/3

Code Optimization

### PR DESCRIPTION
**Pull request by ghostloda**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix code scanning alert-Incorrect conversion between integer types

**Which issue(s) this PR fixes**:
Fixes #551

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by wawa0210** [comment]
@ghostloda thanks your contribution :) , you need to fix the DCO

**Comment by ghostloda** [comment]
> @ghostloda thanks your contribution :) , you need to fix the DCO

ok，fixed

**Comment by wawa0210** [comment]
good job 👍

**Comment by ghostloda** [comment]
@wawa0210   I also want to fix other scanning-Incorrect issues, but I can't see the specific error message. Can you help me?

**Comment by wawa0210** [comment]
> @wawa0210 I also want to fix other scanning-Incorrect issues, but I can't see the specific error message. Can you help me?

I have attached the details in another issues.

**Pull request merged**
