### PR TITLE
Fix pod assignment issue when pod already has a node assigned

### LINKED ISSUE #488: When use set nodeName field, should skip hami-scheduler, this will not trigger the scheduling logic
**What happened**:

**What you expected to happen**:

We should in hook in to check pod whether set nodeName field, and it is need  hami-scheduler, if set and use hami-scheduler, clean it nodeName field, else not exec `vgpu-scheduler-extender` filter step.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

- The output of `nvidia-smi -a` on your host
- Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)
- The hami-device-plugin container logs
- The hami-scheduler container logs
- The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
- Any relevant kernel output lines from `dmesg`

**Environment**:
- HAMi version:
- nvidia driver or other AI device driver version:
- Docker version from `docker version`
- Docker command, image and tag used
- Kernel version from `uname -a`
- Others:

### PR DESCRIPTION
**Pull request by chaunceyjiang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix pod assignment issue when pod already has a node assigned
**Which issue(s) this PR fixes**:
Fixes #488

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by wawa0210** [comment]
> [Codecov](https://app.codecov.io/gh/Project-HAMi/HAMi/pull/564?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Project-HAMi) Report

Can you solve the Codecov Report UT coverage issue?

**Comment by chaunceyjiang** [comment]
> Can you solve the Codecov Report UT coverage issue?

Done.

**Pull request merged**
