### PR TITLE
setup multi-arch build

### PR DESCRIPTION
**Pull request by morlay**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

to build multi arch images with amd64/arm64

**Which issue(s) this PR fixes**:
no

**Special notes for your reviewer**:
-

**Does this PR introduce a user-facing change?**:
no

### CODE REVIEW

**Comment by morlay** [comment]
Known Issue:

lib/mlu/* is x86-64 only.

```shell
$ file lib/mlu/*
lib/mlu/cntopo:          ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=f4e84ebeefefc76c0dbf925d5b28b3c2318f9342, stripped
lib/mlu/libcndev.so:     ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4e4a1717580ce285e50565322b7a87cf3d3d1422, stripped
lib/mlu/smlu-containerd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e3ea08302634487ef73ba64cc55e801d1a085920, with debug_info, not stripped
```

**Comment by CoderTH** [comment]
Is there anything wrong with this pr now?

**Comment by CoderTH** [comment]
Is there anything wrong with this pr now?

**Comment by wawa0210** [comment]
Currently, HAMi images already support multiple architectures.

**Pull request closed without merging**
