### PR TITLE
fix: error happen when allocate iluvatar device

### PR DESCRIPTION
**Pull request by lijm87**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: error 'index out of range [1] with length 1' happen when allocate iluvatar device
fix: exception occurred while creating multiple pods with iluvatar gpu concurrently

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by archlitchi** [comment]
thanks:) are you using iluvatar devices in HAMI?

**Comment by archlitchi** [comment]
please fix go-lint CI, so it can be integrated

**Comment by lijm87** [comment]
> thanks:) are you using iluvatar devices in HAMI?

yes

**Comment by lijm87** [comment]
> please fix go-lint CI, so it can be integrated

done

**Comment by wawa0210** [comment]
@lijm87 We also need to reabse this PR into a single commit, ths last step 😄

**Comment by lijm87** [comment]
> @lijm87 We also need to reabse this PR into a single commit, ths last step 😄

done

**Comment by wawa0210** [comment]
@lijm87 thanks your contribution, nice job 👍

**Pull request merged**
